/* DO NOT EDIT, file generated by nestjs-i18n */

/* eslint-disable */
/* prettier-ignore */
import { Path } from "nestjs-i18n";
/* prettier-ignore */
export type I18nTranslations = {
    "auth": {
        "signInWithEmail": {
            "userNotFound": string;
            "userDisabled": string;
        };
        "signUpWithEmail": {
            "emailAlreadyExists": string;
            "usernameAlreadyExists": string;
        };
        "verifyAuthCode": {
            "invalidOrExpired": string;
            "accountDeleted": string;
        };
    };
    "email": {
        "verificationEmail": {
            "subject": string;
            "body": string;
            "cta": string;
        };
    };
    "session": {
        "createSessionForUser": {
            "userDisabled": string;
        };
    };
    "user": {
        "createUser": {
            "emailAlreadyExists": string;
            "usernameAlreadyExists": string;
        };
        "searchUsers": {
            "invalidStatus": string;
        };
    };
    "validation": {
        "notEmpty": string;
        "invalidEmail": string;
        "username": {
            "noSpecialCharacters": string;
            "invalidLength": string;
        };
    };
};
/* prettier-ignore */
export type I18nPath = Path<I18nTranslations>;
